### ISSUE TITLE
Odd behaviors with 1.0.2 - file changes won't save; only runs check on VS Code launch

### ISSUE THREAD

**Issue by magnum6actual** [movebit/aptos-move-analyzer#12]
Some strange behavior with 1.0.2.  I see two things happening:

1) If there is an unresolved error in a file, changes to another file can't be/aren't saved. Once that error is resolved, changes to the other files can be saved.

2) The analyzer is only identifying problems once when VS Code loads.  The identified issues remain in the problem window until VS Code is reloaded.

I demonstrate this sequence here:

https://youtu.be/uJ2PLuocTEk

**Comment by robinlzw** [comment]
We are currently dealing with another bug, which we will address this issue next week. Thank you for providing feedback.

**Comment by robinlzw** [comment]
We will start dealing with this issue this week

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/aptos-move-analyzer/commit/a29476e8a1aa9db4c1f8730dc330cf408bd4d87f; and we released lsp-server about aptos-move-analyzer v1.0.4
