### ISSUE TITLE
enums not recognized

### ISSUE THREAD

**Issue by magnum6actual** [movebit/aptos-move-analyzer#5]
enums from Move 2.0 (AIP-91, live with v1.18.0) are not recognized.  Use of enums yields the following in Problems:
```
[{
	"resource": "/Users/wayneculbreth/Development/aptos-testing/sources/embedding.v2.move",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "unexpected token\nUnexpected 'enum'\"\"",
	"startLineNumber": 11,
	"startColumn": 2,
	"endLineNumber": 11,
	"endColumn": 6
}]
```

**Comment by robinlzw** [comment]
The new syntax will have basic support, such as goto definition, in two weeks.

**Comment by magnum6actual** [comment]
With 1.0.1 of the extension, I get a different error.  Is there a way to enable Move 2 support now, or is it still in the works?

[{
	"resource": "/Users/wayneculbreth/Development/nutrios-protocol/epicuri-framework/sources/embedding.move",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "unsupported language construct\nMove 2 language construct is not enabled: enum types\"\"",
	"startLineNumber": 16,
	"startColumn": 5,
	"endLineNumber": 16,
	"endColumn": 9
}]

**Comment by robinlzw** [comment]
hi @magnum6actual , we fixed at https://github.com/movebit/aptos-move-analyzer/commit/9838e23a49af6d5c121ecac0bf1cb2bfe6b053c4
